version: '3.8'

services:
  # Servicio para la aplicación .NET Core
  app:
    image: ${DOCKER_REGISTRY-}myapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financial-transactions-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDB__ConnectionString=mongodb://mongodb:27017
      - MongoDB__DatabaseName=FinancialTransactionsDB
      - SQLServer__ConnectionString=Server=sqlserver;Database=FinancialTransactionsDB;User=sa;Password=YourPassword123
    ports:
      - "5000:80"  # Mapea el puerto 5000 del host al puerto 80 del contenedor
    depends_on:
      - mongodb
      - sqlserver
    networks:
      - app-network

  # Servicio para MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"  # Expone MongoDB en el puerto 27017
    networks:
      - app-network

  # Servicio para SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123
    ports:
      - "1433:1433"  # Expone SQL Server en el puerto 1433
    networks:
      - app-network
    volumes:
      - sqlserver_data:/var/opt/mssql

# Volúmenes persistentes para MongoDB y SQL Server
volumes:
  mongodb_data:
    driver: local
  sqlserver_data:
    driver: local

# Redes definidas para permitir que los contenedores se comuniquen entre sí
networks:
  app-network:
    driver: bridge
